// ============================================================
// movies.js — All Movie Data
// Tamil & Hindi movies with showtimes
// ============================================================

const MOVIES = [

  // ════════════════════════════════
  // TAMIL MOVIES
  // ════════════════════════════════
  {
    id: 1,
    lang: 'tamil',
    title: 'JANA NAYAGAN',
    tagline: '"You guys will live in my heart."',
    year: 2026,
    duration: '2h 45m',
    rating: 'U/A',
    imdb: '8.2',
    rt: '89%',
    genre: ['Tamil', 'Action', 'Thriller', 'Political'],
    director: 'H. Vinoth',
    cast: ['Thalapathy Vijay', 'Pooja Hegde', 'Bobby Deol', 'Gautham Menon', 'Prakash Raj', 'Mamitha Baiju'],
    desc: "Jana Nayagan is Superstar Vijay's farewell film before his political entry. A grand political action thriller directed by H. Vinoth with music by Anirudh Ravichander. An ex-cop pulled into a battle bigger than vengeance when ideological rivals collide. Released for Pongal 2026 and smashed all records.",
    get poster() { return IMGS.jana_poster; },
    get banner() { return IMGS.jana_banner; },
    bg: 'linear-gradient(135deg,#1a0530,#3a0a60,#0a0415)',
    stdPrice: 300,
    vipPrice: 520,
    isNew: true,
    isHot: true,
    showtimes: [
      { id: 'jn1', hall: 'PVR IMAX Chennai',  time: '9:30 AM',  format: 'IMAX',         price: 520, avail: 18 },
      { id: 'jn2', hall: 'SPI Luxe Chennai',  time: '12:45 PM', format: 'Dolby Atmos',  price: 380, avail: 62 },
      { id: 'jn3', hall: 'Rohini — Screen 1', time: '4:15 PM',  format: 'Standard 4K',  price: 300, avail: 88 },
      { id: 'jn4', hall: 'AGS Cinemas',       time: '7:30 PM',  format: 'Dolby Atmos',  price: 380, avail: 34 },
      { id: 'jn5', hall: 'PVR IMAX Chennai',  time: '10:45 PM', format: 'IMAX',         price: 520, avail: 7  },
    ],
  },

  {
    id: 2,
    lang: 'tamil',
    title: 'COOLIE',
    tagline: '"The revolution starts at the station."',
    year: 2025,
    duration: '2h 49m',
    rating: 'U/A',
    imdb: '6.0',
    rt: '63%',
    genre: ['Tamil', 'Action', 'Crime', 'Thriller'],
    director: 'Lokesh Kanagaraj',
    cast: ['Rajinikanth', 'Nagarjuna', 'Shruti Haasan', 'Aamir Khan', 'Soubin Shahir', 'Upendra'],
    desc: "Rajinikanth's 171st film — a mass action thriller by Lokesh Kanagaraj about a coolie union leader who uncovers a massive crime syndicate while investigating his friend's death. IMAX-scale action with Anirudh's electrifying score.",
    get poster() { return IMGS.coolie_poster; },
    get banner() { return IMGS.coolie_banner; },
    bg: 'linear-gradient(135deg,#0a0208,#250015,#3c001e)',
    stdPrice: 260,
    vipPrice: 440,
    isNew: false,
    isHot: true,
    showtimes: [
      { id: 'co1', hall: 'PVR Screen 3',  time: '10:00 AM', format: 'Dolby Atmos', price: 360, avail: 44 },
      { id: 'co2', hall: 'Inox Hall 2',   time: '1:30 PM',  format: 'Standard 4K', price: 260, avail: 70 },
      { id: 'co3', hall: 'AGS IMAX',      time: '5:00 PM',  format: 'IMAX',        price: 460, avail: 12 },
      { id: 'co4', hall: 'Rohini Hall 3', time: '8:30 PM',  format: 'Standard 4K', price: 260, avail: 55 },
    ],
  },

  {
    id: 3,
    lang: 'tamil',
    title: 'RETRO',
    tagline: '"Love. Laughter. War."',
    year: 2025,
    duration: '2h 36m',
    rating: 'U/A',
    imdb: '7.1',
    rt: '72%',
    genre: ['Tamil', 'Action', 'Romance', 'Drama'],
    director: 'Karthik Subbaraj',
    cast: ['Suriya', 'Pooja Hegde', 'Joju George', 'Jayaram'],
    desc: "Karthik Subbaraj's period action romance featuring Suriya in a dual-shade role exploring love, rage, and redemption across two timelines. Santhosh Narayanan's music. Produced by Jyotika and Suriya.",
    get poster() { return IMGS.retro_poster; },
    banner: null,
    bg: 'linear-gradient(135deg,#100600,#2e1500,#4a2800)',
    stdPrice: 240,
    vipPrice: 400,
    isNew: false,
    isHot: false,
    showtimes: [
      { id: 're1', hall: 'SPI Screen 5',    time: '11:00 AM', format: 'Standard 4K', price: 240, avail: 60 },
      { id: 're2', hall: 'PVR Hall 4',      time: '3:00 PM',  format: 'Dolby Atmos', price: 340, avail: 40 },
      { id: 're3', hall: 'Sathyam Hall 1',  time: '6:30 PM',  format: 'Standard 4K', price: 240, avail: 80 },
    ],
  },

  {
    id: 4,
    lang: 'tamil',
    title: 'THUG LIFE',
    tagline: '"A life lived on the edge."',
    year: 2025,
    duration: '2h 28m',
    rating: 'U/A',
    imdb: '5.8',
    rt: '55%',
    genre: ['Tamil', 'Action', 'Crime'],
    director: 'Mani Ratnam',
    cast: ['Kamal Haasan', 'Trisha', 'Silambarasan TR', 'Ali Fazal'],
    desc: "Mani Ratnam's crime drama featuring Kamal Haasan in a gritty tale of loyalty and betrayal in the Mumbai underworld. Despite mixed reviews, Kamal's towering performance and Mani Ratnam's visual poetry elevate this beyond its genre.",
    get poster() { return IMGS.thug_poster; },
    banner: null,
    bg: 'linear-gradient(135deg,#050505,#0f0f1a,#1a1a30)',
    stdPrice: 220,
    vipPrice: 380,
    isNew: false,
    isHot: false,
    showtimes: [
      { id: 'tl1', hall: 'Inox Screen 2', time: '12:00 PM', format: 'Standard 4K', price: 220, avail: 90 },
      { id: 'tl2', hall: 'PVR Hall 5',    time: '4:30 PM',  format: 'Standard 4K', price: 220, avail: 70 },
      { id: 'tl3', hall: 'SPI Screen 3',  time: '8:00 PM',  format: 'Dolby Atmos', price: 320, avail: 45 },
    ],
  },

  // ════════════════════════════════
  // HINDI MOVIES
  // ════════════════════════════════
  {
    id: 5,
    lang: 'hindi',
    title: 'DHURANDHAR',
    tagline: '"Break the nexus. From within."',
    year: 2025,
    duration: '3h 34m',
    rating: 'A',
    imdb: '8.3',
    rt: '82%',
    genre: ['Hindi', 'Action', 'Spy Thriller', 'Crime'],
    director: 'Aditya Dhar',
    cast: ['Ranveer Singh', 'Akshaye Khanna', 'Sanjay Dutt', 'R. Madhavan', 'Arjun Rampal', 'Sara Arjun'],
    desc: "India's highest-grossing film of 2025. A RAW operative infiltrates Karachi's criminal underworld to dismantle a terror nexus targeting India. Inspired by the IC-814 hijacking and 2008 Mumbai attacks. Ranveer Singh is career-defining as Hamza Ali Mazari in this 3.5-hour espionage epic by Uri director Aditya Dhar.",
    get poster() { return IMGS.dhurandhar_poster; },
    get banner() { return IMGS.dhurandhar_banner; },
    bg: 'linear-gradient(135deg,#040810,#0a1828,#0f2040)',
    stdPrice: 320,
    vipPrice: 560,
    isNew: false,
    isHot: true,
    showtimes: [
      { id: 'dh1', hall: 'PVR IMAX',          time: '10:00 AM', format: 'IMAX',         price: 560, avail: 22 },
      { id: 'dh2', hall: 'Inox Luxe 1',        time: '1:00 PM',  format: 'Dolby Atmos',  price: 400, avail: 55 },
      { id: 'dh3', hall: 'Cinepolis Hall 3',   time: '5:30 PM',  format: 'Standard 4K',  price: 320, avail: 88 },
      { id: 'dh4', hall: 'PVR IMAX',          time: '9:15 PM',  format: 'IMAX',         price: 560, avail: 8  },
      { id: 'dh5', hall: 'Inox Luxe 1',        time: '11:59 PM', format: 'Dolby Atmos',  price: 400, avail: 35 },
    ],
  },

  {
    id: 6,
    lang: 'hindi',
    title: 'WAR 2',
    tagline: '"The war never ends."',
    year: 2025,
    duration: '2h 50m',
    rating: 'U/A',
    imdb: '6.8',
    rt: '68%',
    genre: ['Hindi', 'Action', 'Spy', 'Thriller'],
    director: 'Ayan Mukerji',
    cast: ['Hrithik Roshan', 'Jr. NTR', 'Kiara Advani', 'Deepika Padukone'],
    desc: "YRF Spy Universe expands as Kabir faces a new adversary in a globe-trotting action spectacle. Hrithik Roshan and Jr. NTR ignite the screen in a clash of titans, directed by Ayan Mukerji with jaw-dropping stunts.",
    get poster() { return IMGS.war2_poster; },
    get banner() { return IMGS.war2_banner; },
    bg: 'linear-gradient(135deg,#0a0000,#200010,#380026)',
    stdPrice: 280,
    vipPrice: 480,
    isNew: false,
    isHot: true,
    showtimes: [
      { id: 'w21', hall: 'PVR Hall 2',        time: '10:30 AM', format: 'IMAX',        price: 480, avail: 30 },
      { id: 'w22', hall: 'Inox Screen 4',      time: '2:00 PM',  format: 'Standard 4K', price: 280, avail: 65 },
      { id: 'w23', hall: 'Cinepolis Screen 2', time: '6:00 PM',  format: 'Dolby Atmos', price: 380, avail: 48 },
      { id: 'w24', hall: 'PVR Hall 2',        time: '9:30 PM',  format: 'IMAX',        price: 480, avail: 14 },
    ],
  },

  {
    id: 7,
    lang: 'hindi',
    title: 'PUSHPA 2',
    tagline: '"Pushpa naam sunke flower samjhe kya?"',
    year: 2024,
    duration: '3h 20m',
    rating: 'U/A',
    imdb: '7.6',
    rt: '80%',
    genre: ['Hindi', 'Action', 'Drama', 'Crime'],
    director: 'Sukumar',
    cast: ['Allu Arjun', 'Rashmika Mandanna', 'Fahadh Faasil', 'Jagapathi Babu'],
    desc: "The record-breaking sequel to Pushpa: The Rise. Pushpa Raj expands his sandalwood empire while battling Bhanwar Singh Shekawat. Allu Arjun's iconic performance and Devi Sri Prasad's electrifying music combine for the highest-grossing Indian film ever.",
    get poster() { return IMGS.pushpa_poster; },
    banner: null,
    bg: 'linear-gradient(135deg,#0a0800,#1e1500,#3a2800)',
    stdPrice: 260,
    vipPrice: 440,
    isNew: false,
    isHot: false,
    showtimes: [
      { id: 'p21', hall: 'Inox Hall 3',   time: '11:30 AM', format: 'Standard 4K', price: 260, avail: 75 },
      { id: 'p22', hall: 'PVR Screen 5',  time: '3:30 PM',  format: 'Dolby Atmos', price: 360, avail: 50 },
      { id: 'p23', hall: 'SPI Hall 2',    time: '7:00 PM',  format: 'Standard 4K', price: 260, avail: 88 },
    ],
  },
];

// My Bookings history
const MY_BOOKINGS = [
  {
    id: 'CMJ001',
    movie: 'JANA NAYAGAN',
    time: 'Jan 08 · 7:30 PM',
    hall: 'SPI Luxe',
    seats: 'D5 · D6 · D7',
    status: 'conf',
    get poster() { return IMGS.jana_poster; },
    paid: '₹1,170',
    method: 'GPay UPI',
  },
  {
    id: 'CMD002',
    movie: 'DHURANDHAR',
    time: 'Dec 05 · 5:30 PM',
    hall: 'Cinepolis',
    seats: 'F3 · F4',
    status: 'past',
    get poster() { return IMGS.dhurandhar_poster; },
    paid: '₹670',
    method: 'HDFC Credit Card',
  },
];

// Upcoming releases
const UPCOMING = [
  { title: 'THALAPATHY 69',    lang: 'tamil', date: 'Apr 14, 2026',  director: 'A.R. Murugadoss', cast: 'Vijay Antony, Nithya Menen', bg: 'linear-gradient(135deg,#1a0a00,#3a1800)' },
  { title: 'SULTAN OF DELHI 2',lang: 'hindi', date: 'Jun 2026',      director: 'Milan Luthria',   cast: 'Tahir Raj Bhasin',          bg: 'linear-gradient(135deg,#00101a,#002030)' },
  { title: 'VIKRAM 2',         lang: 'tamil', date: 'Diwali 2026',   director: 'Lokesh Kanagaraj',cast: 'Kamal Haasan, Vijay',       bg: 'linear-gradient(135deg,#0a0015,#200030)' },
];
